services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=langs2brain.settings
    env_file:
      - .env

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A langs2brain worker --loglevel=info --uid=nobody
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=langs2brain.settings
    env_file:
      - .env
