# Generated by Django 5.2.1 on 2025-05-21 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Phrase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("native_text", models.TextField()),
                ("target_text", models.TextField()),
                ("cefr", models.CharField(max_length=3)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General"),
                            ("IDIOM", "Idiom"),
                            ("PROVERB", "Proverb"),
                            ("QUOTE", "Quote"),
                        ],
                        default="GENERAL",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=100)),
                ("language", models.CharField(default="en_GB", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="LessonPhrase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.lesson",
                    ),
                ),
                (
                    "phrase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.phrase",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="lesson",
            name="phrases",
            field=models.ManyToManyField(
                through="learning.LessonPhrase", to="learning.phrase"
            ),
        ),
        migrations.AddField(
            model_name="phrase",
            name="words",
            field=models.ManyToManyField(blank=True, to="learning.word"),
        ),
        migrations.CreateModel(
            name="WordTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("translation", models.CharField(max_length=100)),
                ("note", models.CharField(blank=True, max_length=100)),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="learning.word",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LessonFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("TXT", "Text"),
                            ("STUDY", "Study MP3"),
                            ("TRAINING", "Training MP3"),
                        ],
                        max_length=10,
                    ),
                ),
                ("file", models.FileField(upload_to="lessons/")),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="learning.lesson",
                    ),
                ),
            ],
            options={
                "unique_together": {("lesson", "file_type")},
            },
        ),
    ]
