# Generated by Django 5.2.1 on 2025-05-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="number",
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="lessonfile",
            name="file",
            field=models.FileField(unique=True, upload_to="lessons/"),
        ),
        migrations.AlterField(
            model_name="phrase",
            name="cefr",
            field=models.CharField(
                choices=[
                    ("A1", "A1"),
                    ("A2", "A2"),
                    ("B1", "B1"),
                    ("B2", "B2"),
                    ("C1", "C1"),
                    ("C2", "C2"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="wordtranslation",
            name="note",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="lessonphrase",
            unique_together={("lesson", "order")},
        ),
        migrations.AlterUniqueTogether(
            name="word",
            unique_together={("text", "language")},
        ),
        migrations.AlterUniqueTogether(
            name="wordtranslation",
            unique_together={("word", "translation")},
        ),
        migrations.AddIndex(
            model_name="phrase",
            index=models.Index(fields=["cefr"], name="learning_ph_cefr_2d596e_idx"),
        ),
        migrations.AddIndex(
            model_name="phrase",
            index=models.Index(
                fields=["category"], name="learning_ph_categor_1ffc9a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="word",
            index=models.Index(fields=["text"], name="learning_wo_text_fb7d1a_idx"),
        ),
    ]
