openapi: 3.1.0
info:
  title: Langs2Brain Lexical Unit Bulk Translation API
  version: "1.3" # Updated version
  description: |
    Push a source lexical unit (lemma) and its translations (with details like pronunciation, POS, and confidence) into the vocabulary database. This endpoint handles the creation of the source and target lexical units if they do not exist.

servers:
  - url: https://f844-212-175-197-252.ngrok-free.app # ðŸ‘ˆ Update with your current public address
    description: Development Server (via ngrok)

paths:
  /api/lexical-unit-translations/bulk-create/: # <<< PATH UPDATED
    post:
      operationId: bulkCreateLexicalUnitTranslations # <<< operationId updated for clarity
      summary: Create a source lexical unit and add multiple translations
      tags:
        - Lexical Unit Translations
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BulkLexicalUnitTranslation"
      responses:
        "201":
          description: Translations successfully created. Returns a list of the created translation link objects.
        "400":
          description: Validation error (e.g., same primary language, self-translation, malformed language code).

components:
  schemas:
    LexicalUnitInput: # <<< RENAMED from WordInput
      type: object
      required:
        - lemma # <<< RENAMED from word
        - language
      properties:
        lemma: # <<< RENAMED from word
          type: string
          example: "take off"
          description: "The lexical unit's lemma. Will be canonicalized (lowercased, normalized spaces)."
        language:
          type: string
          example: "en-GB"
          description: "BCP47 language code for the lemma."
        part_of_speech:
          type: string
          # <<< UPDATED ENUM from your enums.py
          enum: [noun, verb, adj, adv, pron, prep, conj, interj, num, part, collocation, phrasal_verb, idiom, multi_word_unit, ""]
          example: "phrasal_verb"
          description: "The Part of Speech. If omitted or sent as an empty string, it will be 'Unspecified'."
        pronunciation:
          type: string
          example: "/teÉªk É’f/"
          description: "Optional. IPA or phonetic transcription."

    BulkLexicalUnitTranslation: # <<< RENAMED from BulkWordTranslation
      type: object
      required:
        - source_unit # <<< RENAMED from source_word
        - targets
      properties:
        source_unit: # <<< RENAMED from source_word
          $ref: "#/components/schemas/LexicalUnitInput"
        targets:
          type: array
          minItems: 1
          items:
            $ref: "#/components/schemas/LexicalUnitInput"
        translation_type:
          type: string
          enum: [manual, ai, user, imported] # <<< UPDATED ENUM
          default: manual
          description: "The method by which this translation was obtained."
        confidence:
          type: number
          format: float
          minimum: 0.0
          maximum: 1.0
          example: 0.95
          description: "Optional. A score (0-1) indicating confidence in the translation, typically for 'ai' type."